### ISSUE TITLE
Organize repository as an R package

### ISSUE THREAD

**Issue by magicDGS** [ThomasTaus/Nest#2]
This will allow to install the package using `devtools`. See how here: https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html

For the [Release folder](https://github.com/ThomasTaus/Nest/tree/master/Release), I recommend to create GitHub releases pointing to the commit and upload the zip file as an extra file indicating that it is a packaged library to be install (e.g., `Nest_1.1.3.tar.gz` will be `Nest_1.1.3.lib.tar.gz`).

If you want, I can help here and be a maintainer of the repo to implement some changes and help with the documentation...

**Comment by ThomasTaus** [comment]
Thank you very much for your recommendations. In [poolSeq](https://github.com/ThomasTaus/poolSeq) everything is set up as you suggested. Please use poolSeq instead of Nest, as noted in the Readme file.

Since you pass by my office every time you get a cup of tea, please feel free to drop by and talk.

Cheers,

Thomas
